services:
  mongo:
    image: mongo:8.0
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://root:example@localhost:27017 --quiet
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - mongo_data:/data/db
    networks:
      - space-events-net

  space-events-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: space-events-api
    ports:
      - "3001:3001"
    depends_on:
      mongo:
        condition: service_healthy
        restart: true

    environment:
      MONGO_URI: mongodb://root:example@mongo:27017
    networks:
      - space-events-net

volumes:
  mongo_data:

networks:
  space-events-net:
    driver: bridge
